---
- name: Get cluster interface
  set_fact:
    cluster_interface: "{{ item }}"
  when: 
  - hostvars[inventory_hostname]['ansible_' + item]['ipv4'] is defined
  - hostvars[inventory_hostname]['ansible_' + item]['ipv4']['address'] == ansible_host
  with_items:
    - "{{ ansible_interfaces }}"

- name: Increase VRRP Priority of lead controller higher for determinism
  set_fact:
    vrrp_pri: "{{ vrrp_pri  | int + 1 }}"
  when: ansible_hostname == lead_controller

- name: Add VRRP config
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf

- name: Start/Enable VRRP
  service:
    name: keepalived
    enabled: true
    state: restarted

- name: Add HAProxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Start/Enable HAProxy
  service:
    name: haproxy
    enabled: true
    state: restarted

- name: Wait for API Reachability
  wait_for:
    host: "{{ vrrp_virtual_ip }}"
    port: "{{ haproxy_listen_port }}"
    delay: 2