---

  ###
  # Install HA components
  #

- name: Prep Debian
  include_tasks: global/prep-debian.yml
  when: ansible_os_family == 'Debian'

- name: Prep RedHat
  include_tasks: global/prep-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Keepalived, HAProxy
  package: 
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ packages }}"

- name: configure global settings
  include_tasks: global/global-config.yml

- name: Pull kubernetes images
  command: kubeadm config images pull --v=5

- name: Generate release notes
  include_tasks: global/generate_release_notes.yml
  when: 
  - generate_release_notes | bool

  ###
  # End play if set to only install and not configure
  #

- meta: end_play
  when: install_only | bool
  
  ###
  # Enable HA networking on controller nodes
  #

- name: Setup HA networking
  include_tasks: ha/ha-api-network.yml
  when: inventory_hostname in groups.controllers

  ###
  # Set a lead controller based on the alphanumerically lowest ansible_hostname if not already defined
  # Best practice: define explicitly as a global var
  #

- name: Set lead controller if not already defined
  set_fact:
    lead_controller: "{{ groups.controllers | min }}"
  run_once: true
  when: lead_controller is not defined

  ###
  # Install kubernetes and deploy the cluster
  #

- name: Deploy cluster
  include_tasks: deploy-nodes/deploy-cluster.yml
  
  ###
  # Set hosts kubeconfig
  #

- name: Download kubeconfig to host
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: "{{ host_kubeconfig_dest }}"
    flat: true
  when: 
  - inventory_hostname == lead_controller
  - set_host_kubeconfig | bool
  tags: get-kubeconfig
  
  ###
  # Remove taint from controllers
  #

- name: Set taint status on controllers
  import_tasks: taints.yml
  when: inventory_hostname in groups.controllers