---

  ###
  # Install packages and add global config
  #

- name: Install packages
  include_tasks: global/install-packages.yml

- name: Generate release notes
  include_tasks: global/generate_release_notes.yml
  when: 
  - generate_release_notes is true

- name: configure global settings
  include_tasks: global/global-config.yml

  ###
  # End play if this is run by packer to build a vagrant box image
  #

- meta: end_play
  when: build_base_image is true

  ###
  # Enable HA networking on controller nodes
  #

- name: Setup HA networking
  include_tasks: ha/ha-api-network.yml
  when: ansible_hostname in groups.controllers

  ###
  # Set a lead controller based on the alphanumerically lowest ansible_hostname if not already defined
  # Best practice: define explicitly as a global var
  #

- name: Set lead controller if not already defined
  set_fact:
    lead_controller: "{{ groups.controllers | min }}"
  run_once: true
  when: lead_controller is not defined

  ###
  # Build Cluster
  #

- name: Deploy lead controller
  include_tasks: deploy-nodes/lead-controller.yml
  when: ansible_hostname == lead_controller

- name: Deploy remaining controllers
  include_tasks: deploy-nodes/controllers.yml
  when:
  - ansible_hostname in groups.controllers
  - ansible_hostname != lead_controller

- name: Deploy workers
  include_tasks: deploy-nodes/workers.yml
  when: 
  - groups.workers is defined
  - ansible_hostname in groups.workers
  
  ###
  # Set hosts kubeconfig
  #

- name: Download kubeconfig to host
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: "{{ host_kubeconfig_dest }}"
    flat: true
  when: 
  - ansible_hostname == lead_controller
  - set_host_kubeconfig | bool
  tags: get-kubeconfig

  ###
  # Set VRRP to track HAProxy
  #

- name: Track HA Proxy
  import_tasks: ha/track-haproxy.yml
  when: ansible_hostname in groups.controllers

  ###
  # Remove taint from controllers
  #

- name: Set taint status on controllers
  import_tasks: taints.yml
  when: ansible_hostname in groups.controllers

  ###
  # Install optional extras
  #

- name: Install metrics server
  include_tasks: optional-extras/metrics-server.yml
  when: 
  - ansible_hostname == lead_controller
  - install_metrics_server | bool

- name: Install NFS Provisioner - Client packages
  include_tasks: optional-extras/nfs-common.yml
  when: install_nfs_provisioner | bool

- name: Install NFS Provisioner - Server Side
  include_tasks: optional-extras/nfs-provisioner.yml
  when: 
  - ansible_hostname == lead_controller
  - install_nfs_provisioner | bool

- name: Install Metallb
  include_tasks: optional-extras/metallb.yml
  when: 
  - ansible_hostname == lead_controller
  - install_metallb | bool

- name: Install Kubernetes Dashboard
  include_tasks: optional-extras/kubernetes-dashboard.yml
  when: 
  - ansible_hostname == lead_controller
  - install_kubernetes_dashboard | bool