---

###
# Get token for controllers to join cluster
#

- name: Get cluster control-plane certificate key
  ansible.builtin.command: kubeadm token create
  register: token

- name: Get cluster control-plane certificate key
  ansible.builtin.command: kubeadm init phase upload-certs --upload-certs
  register: cert_key

- name: Get CA Key hash
  ansible.builtin.shell:
  register: ca_hash
