---

###
# Setup kubeconfig on controllers
#

- name: Ensure .kube directory exists.
  file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    mode: 0755
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"

- name: Symlink kubectl's admin.conf to ~/.kube/conf
  file:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    state: link
    mode: 0644
    force: true
