---

###
# Setup kubeconfig for the ansible user
#

- name: Ensure .kube directory exists.
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    mode: 0755
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
  when: set_user_kubeconfig | bool

- name: Symlink kubectl's admin.conf to /home/{{ ansible_user }}/.kube/config
  ansible.builtin.file:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    state: link
    mode: 0644
    force: true
  when: set_user_kubeconfig | bool

###
# Setup kubeconfig for the root user
#
  
- name: Ensure .kube directory exists.
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: 0755

- name: Symlink the kubectl admin.conf to ~/.kube/conf.
  ansible.builtin.file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link
    mode: 0644
