---
###
# Install metrics server
#

- name: Download metrics server manifest
  get_url:
    url: "{{ item.url }}"
    dest: "/tmp/{{ item.filename }}"
    mode: "0664"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_items:
    - url: https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
      filename: metrics-server.yml

- name: Deploy Metrics Server
  become: false
  kubernetes.core.k8s:
    state: present
    src: "/tmp/metrics-server.yml"

###
# Add --kubelet-insecure-tls argument. TLS encryption not implemented at this time.
#

- name: Apply multiple patch operations to an existing Pod
  become: false
  kubernetes.core.k8s_json_patch:
    kind: Deployment
    namespace: kube-system
    name: metrics-server
    patch:
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --kubelet-insecure-tls
