---

###
# Create an NFS Server on the controller
# Exports /share to the host only network
# Installs NFS Subdir External Provisioner for dynamic provisioning of NFS storage
# - https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner
#

- name: Installing NFS Server Packages
  apt:
    name: nfs-kernel-server
    state: "present"

- name: Create share directories
  file:
    dest: "/share"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "u=rwx,g=rx,o=rx"
    state: "directory"

- name: config | Configuring /etc/exports
  lineinfile:
    line: "/share    {{ nfs_subnet }}(rw,sync,no_subtree_check,no_root_squash)"
    path: /etc/exports
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
    create: yes
  tags: export

- name: restart nfs-kernel-server
  service:
    name: "nfs-kernel-server"
    state: "restarted"
    enabled: true

- name: restart nfs-server
  service:
    name: "nfs-server"
    state: "restarted"
    enabled: true

- name: Add NFS Subdir External Provisioner Helm Repository
  become: false
  kubernetes.core.helm_repository:
    name: nfs-subdir-external-provisioner
    repo_url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
  tags: nfs-provision

- name: Deploy NFS Subdir External Provisioner
  become: false
  kubernetes.core.helm:
    name: nfs-subdir-external-provisioner
    chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    release_namespace: nfs-system
    create_namespace: true
    values:
      nfs:
        server: "{{ ansible_host }}"
        path: "/share"