---
- name: Restart HAProxy
  ansible.builtin.service:
    name: haproxy
    enabled: true
    state: restarted

- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted

- name: Restart kubelet
  ansible.builtin.service:
    name: kubelet
    state: restarted
