---

###
# Enable CRI plugin and set cgroup driver to systemd as per:
# https://kubernetes.io/docs/setup/production-environment/container-runtimes/#forwarding-ipv4-and-letting-iptables-see-bridged-traffic
#

- name: Remove cri from disabled plugins list
  ansible.builtin.ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    state: absent
    line: disabled_plugins = ["cri"]

- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted

###
# Disable swap
#

- name: Disable swap
  ansible.builtin.command: swapoff -av

- name: Remove swap ftsab entires
  ansible.builtin.lineinfile:
    path: /etc/fstab
    state: absent
    regexp: "^%swap"

###
# Setup IP Tables as per:
# https://kubernetes.io/docs/setup/production-environment/container-runtimes/#forwarding-ipv4-and-letting-iptables-see-bridged-traffic
#

- name: Set load peristence for br_netfilter and overlay modules
  become: true
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/kubernetes.conf
    line: "{{ item }}"
    create: true
    owner: root
    group: root
    mode: "0644"
  with_items:
  - br_netfilter
  - overlay

- name: Ensure br_netfilter and overlay modules are loaded
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  with_items:
  - br_netfilter
  - overlay

- name: Configure IP Tables
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
  with_items:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward
