---
###
# Install Kubernetes & Project Dependencies
#

- name: Add an apt signing key for Kubernetes
  ansible.builtin.apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Add apt repository for Kubernetes
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - deb https://apt.kubernetes.io/ kubernetes-xenial main
